# Generated by Django 4.2 on 2023-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
