# Generated by Django 4.2 on 2023-05-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_detailsurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
